[project]
name = "clickhouse-function-reference"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "docker>=7.1.0",
    "joblib>=1.5.1",
    "loguru>=0.7.3",
    "requests>=2.32.4",
]
