import requests


function_pages = [
    "arithmetic-functions",
    "array-functions",
    "array-join",
    "udf",
    "bit-functions",
    "bitmap-functions",
    "comparison-functions",
    "conditional-functions",
    "date-time-functions",
    "ext-dict-functions",
    "distance-functions",
    "ym-dict-functions",
    "geo/coordinates",
    "geo/geohash",
    "geo/h3",
    "geo/polygons",
    "geo/s2",
    "geo/svg",
    "encoding-functions",
    "encryption-functions",
    "files",
    "hash-functions",
    "in-functions",
    "ip-address-functions",
    "introspection",
    "json-functions",
    "logical-functions",
    "machine-learning-functions",
    "tuple-map-functions",
    "math-functions",
    "nlp-functions",
    "functions-for-nulls",
    "other-functions",
    "random-functions",
    "string-replace-functions",
    "rounding-functions",
    "string-search-functions",
    "splitting-merging-functions",
    "string-functions",
    "time-series-functions",
    "time-window-functions",
    "tuple-functions",
    "type-conversion-functions",
    "ulid-functions",
    "url-functions",
    "uuid-functions",
    "uniqtheta-functions"
]

function_doc_template = "https://clickhouse.com/docs/en/sql-reference/functions/{page}/"
